
import { StorageItem } from '@/lib/types'

export const dummyStorageItems: StorageItem[] = [
  {
    id: '1',
    name: 'Q1 Reports',
    type: 'folder',
    uploadedBy: 'Sarah Johnson',
    fileSize: '-',
    dateModified: new Date('2024-03-15'),
  },
  {
    id: '2',
    name: 'Project Proposal.pdf',
    type: 'file',
    uploadedBy: 'Mike Chen',
    fileSize: '3.2 MB',
    dateModified: new Date('2024-03-20'),
  },
  {
    id: '3',
    name: 'Design Assets',
    type: 'folder',
    uploadedBy: 'Emma Davis',
    fileSize: '-',
    dateModified: new Date('2024-03-18'),
  },
  {
    id: '4',
    name: 'Presentation.pptx',
    type: 'file',
    uploadedBy: 'John Smith',
    fileSize: '5.8 MB',
    dateModified: new Date('2024-03-22'),
  },
  {
    id: '5',
    name: 'Budget Spreadsheet.xlsx',
    type: 'file',
    uploadedBy: 'Rachel Lee',
    fileSize: '1.4 MB',
    dateModified: new Date('2024-03-19'),
  },
  {
    id: '6',
    name: 'Marketing Materials',
    type: 'folder',
    uploadedBy: 'David Wilson',
    fileSize: '-',
    dateModified: new Date('2024-03-17'),
  },
  {
    id: '7',
    name: 'Meeting Notes.docx',
    type: 'file',
    uploadedBy: 'Lisa Anderson',
    fileSize: '0.8 MB',
    dateModified: new Date('2024-03-21'),
  },
  {
    id: '8',
    name: 'Code Repository',
    type: 'folder',
    uploadedBy: 'Alex Turner',
    fileSize: '-',
    dateModified: new Date('2024-03-16'),
  },
  {
    id: '9',
    name: 'Client Contract.pdf',
    type: 'file',
    uploadedBy: 'Sarah Johnson',
    fileSize: '2.1 MB',
    dateModified: new Date('2024-03-20'),
  },
  {
    id: '10',
    name: 'Archive',
    type: 'folder',
    uploadedBy: 'Mike Chen',
    fileSize: '-',
    dateModified: new Date('2024-03-14'),
  },
]
